# Generated by Django 5.1.2 on 2024-12-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartoon',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cartoon',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
